export interface Post {
    brand:String;
    model:String;
    condition:String;
    location:String;
    screenSize:String;
    screenDisplay: String;
    price:number;
    quantity: number;
    description:String;
    discount:number;
    processorBrand: String;
    processorModel: String;
    processorCore: String;
    processorGen: String;
    graphics: String;
    graphicsBrand: String;
    graphicsModel: String;
    graphicsMemory:String;
    graphicsSize: String;
    graphicsBrand1:String;
    graphicsModel1: String;
    graphicsSize1: String;
    graphicsMemory1: String;
    processorSpeed: number;
    turboSpeed:number;
    hdNo: String;
    hdBrand: String;
    hdType: String;
    hdSize:String;
    hdBrand1: String;
    hdType1: String;
    hdSize1: String;
    ramBrand: String;
    hdBrand2: String;
    hdType2: String;
    hdSize2: String;
    hdBrand3: String;
    hdType3: String;
    hdSize3: String;
    ramType: String;
    ramSize: String;
    cells: String;
    power: String;
    voltage: String;
    current:String;
    duration: String;
    screenType:String;
    boardType:String;
    ramFor:String;
    color:String;
    size:String;
    speed:String;
    mouseType:String;
    usbSize:String;
    padType:String;
    encloseType:String;
    cableType:String;
    cableSize:String;
    category:String;
    subcategory:String;
    title:String;
    }